//$TOY_SCALAR_PATH/rtl/icache_2/toy_pack.sv
$TOY_SCALAR_PATH/rtl/icache_2/icache_top_scalar.sv
//$TOY_SCALAR_PATH/rtl/icache_2/cmn_lead_one.sv
//$TOY_SCALAR_PATH/rtl/icache_2/cmn_onehot2bin.sv
$TOY_SCALAR_PATH/rtl/icache_2/cmn_onehot2bin2.sv
$TOY_SCALAR_PATH/rtl/icache_2/icache_req_arbiter.sv
$TOY_SCALAR_PATH/rtl/icache_2/fix_priority_arb.sv
$TOY_SCALAR_PATH/rtl/icache_2/icache_tag_pipe_2tagram.sv
$TOY_SCALAR_PATH/rtl/icache_2/icache_prefetch_engine.sv
$TOY_SCALAR_PATH/rtl/icache_2/icache_mshr_entry.sv
$TOY_SCALAR_PATH/rtl/icache_2/icache_mshr_file.sv
$TOY_SCALAR_PATH/rtl/icache_2/icache_data_array_ctrl.sv
$TOY_SCALAR_PATH/rtl/icache_2/pre_allocate.sv
$TOY_SCALAR_PATH/rtl/icache_2/sync_fifo.sv
$TOY_SCALAR_PATH/rtl/icache_2/vrp_arb.sv
$TOY_SCALAR_PATH/rtl/icache_2/arb_vrp.sv
$TOY_SCALAR_PATH/rtl/icache_2/arb_fp.sv
$TOY_SCALAR_PATH/rtl/icache_2/v_en_decode.sv
$TOY_SCALAR_PATH/rtl/icache_2/cmn_real_mux_onehot.sv
$TOY_SCALAR_PATH/rtl/icache_2/icache_adapter.sv
$TOY_SCALAR_PATH/rtl/icache_2/icache_mem.sv
$TOY_SCALAR_PATH/rtl/icache_2/mem/toy_itcm.sv
$TOY_SCALAR_PATH/rtl/icache_2/mem/toy_imem_model.sv
//data/usr/xuemy/try/icache_2r_v1/icache/icache_top_v2_tb.sv
